package Alphumanservice::RouteMap;

use strict;
use base 'Class::Accessor::Fast';

# autogenerated by woax-toolkit.pl
# if you want edit  - edit Map.pm file for service and run "woax-toolkit.pl -a service -n YourServiceName "
# !!! DONT EDIT THIS FILE !!! #

my $rules = [
    { path => '/ahs/auth$', class => 'Alphumanservice::REST::Auth::SP' },
    
    { path => '/ahs/goals', class => 'Alphumanservice::REST::Goals::SP' },
    
    { path => '/ahs/contacts', class => 'Alphumanservice::REST::Contacts::SP' },
    
    { path => '/ahs/discharge', class => 'Alphumanservice::REST::DischargeData::SP' },
    
    { path => '/ahs/userdata', class => 'Alphumanservice::REST::UserData::SP' },
    
    { path => '/ahs/passport', class => 'Alphumanservice::REST::PassportData::SP' },
    
    { path => '/ahs/geodata', class => 'Alphumanservice::REST::GeoData::SP' },
    
    { path => '/ahs/ensurance', class => 'Alphumanservice::REST::EnsuranceData::SP' },
    
    { path => '/part-form/part', class => 'Alphumanservice::Page::Part' },
  
    { path => '/part-form/goals', class => 'Alphumanservice::Page::Goals' },
    
    { path => '/part-form/place', class => 'Alphumanservice::Page::Place' },
    
];

sub get_appid {
    return 'alphumanservice';
}

sub get_rules { return $rules; }

1;

__END__
