package [%app_name%]::RouteMap;

use strict;
use base 'Class::Accessor::Fast';

# autogenerated by woax-toolkit.pl
# if you want edit  - edit Map.pm file for service and run "woax-toolkit.pl -a service -n YourServiceName "
# !!! DONT EDIT THIS FILE !!! #

my $rules = [
    [%FOREACH item IN rules%]
    { path => '[%item.path%]', class => '[%item.class%]' },
    [%END%]
];

sub get_appid {
    return '[%lc_app_name%]';
}

sub get_rules { return $rules; }

1;

__END__
