package Alproute::RouteMap;
use strict;

# autogenerated by woax-toolkit.pl
# if you want edit  - edit Map.pm file for service and run "woax-toolkit.pl -a service -n YourServiceName "
# !!! DONT EDIT THIS FILE !!! #

my $rules = [
    
    { path => '/rest/alproute', class => 'Alproute::REST::RouteManager::SP' },
    { path => '/alproute/view', class => 'Alproute::Page::Frontend::View' },
];
sub get_rules { return $rules; }

1;

__END__
